"""
worksheet_generator.py

Weekly worksheet generator for EngageKids AI — VISUAL worksheets, not
paragraphs of instructions.

v3 changes (from v2), driven by:
  - "Developmental milestones and the EYLF/NQS" (Community Child Care
    Co-operative Ltd, EYLF Practice Based Resources) — the educator's own
    reference document, and
  - direct feedback that 1-3y had too few activity types, that a worksheet
    should never be "draw one circle" and stop, and that hollow/outline
    letters are a good example of a stretch task for the 3-4y band.

  1. Age bands are now FIVE groups instead of three, matching the doc's own
     breakpoints where the doc gives them (0-4mo/4-8mo/8-12mo collapsed
     into one "Babies 0-1" band; 1-2y and 2-3y are the doc's own bands).
     The doc's "3 to 5 years" section is NOT split by the source — we
     split it ourselves into "Preschool 3-4" and "Pre-K 4-5" by reading
     which named skills are earlier vs later within that one section
     (tripod grasp / cutting paper / imitating shapes -> 3-4; "may write
     some numbers and letters" / "counts five to ten things" -> 4-5).
     That split is our own interpolation, not a line the document states.
  2. Babies 0-1 years gets NO worksheet. The doc's 0-12mo milestones are
     entirely pre-mark-making (tracks objects, reaches/grasps, points to
     communicate only emerges at 8-12mo) so instead the app produces
     "Look & Point" cards — one big high-contrast shape for the educator
     to hold up and narrate. These are not something the baby completes.
  3. Every other age band has 4-7 age-appropriate categories now (was as
     few as 2 for 1-3y in v2), each tagged to the specific milestone line
     that justifies it — see the comments on CATEGORY_DEFS.
  4. Every worksheet now has a base task PLUS an optional "bonus/stretch"
     section one difficulty step up, generated by the same renderer, so a
     worksheet is never a single static item (the "not just one circle"
     requirement). Non-tiered types (coloring pages, point-and-name cards,
     look & point cards, free scribble) are single-page by nature and are
     not stretched.
  5. New renderers grounded directly in specific milestone lines:
       - look_point            (0-1y: tracks contrast/patterns/faces)
       - point_and_name_shapes (1-2y/2-3y: "points to objects when named",
                                 "recognises...by pointing")
       - point_and_name_body   (1-2y: "knows some body parts",
                                 "points to body parts in a game")
       - first_scribbles       (1-2y: "scribbles with pencil or crayon
                                 held in fist" — free mark-making, not a
                                 precise trace)
       - big_trace             (2-3y/3-4y: "uses a pencil to draw or
                                 scribble in circles and lines",
                                 "imitates variety of shapes in drawing")
       - count_aloud           (2-3y: "begins to count with numbers" —
                                 verbal only, no writing skill yet)
       - hollow_letter_fill    (3-4y: early letter-shape work ahead of
                                 full writing — outline letters to color
                                 in, a stepping stone before "copies
                                 letters" / "writes some letters" at 4-5y)
  6. Difficulty baselines are per-band again (was per-3-band before).
  7. Worksheets-per-week is still educator-configurable; Babies 0-1 uses
     the same setting but for "cards" rather than worksheets.

The page a child sees is still built directly in code as colorful SVG
shapes/figures arranged in a grid — never LLM-written prose. This
guarantees every worksheet is genuinely visual/colorful and low-text,
regardless of what the educator typed in (or didn't type in).

The AI (Groq) is used ONLY for a short title + one-line educator tip, and
that call is optional — if it fails for any reason, a deterministic title
is used instead, so the worksheet never depends on the AI writing well.
"""

import datetime
import random
import streamlit as st

from worksheet_db import (
    init_worksheet_tables,
    save_worksheet,
    get_worksheets_for_week,
    get_recent_titles,
    save_feedback,
    get_latest_feedback,
    get_worksheet_history,
    get_worksheets_per_week,
    set_worksheets_per_week,
    delete_worksheet,
)

# ---------------------------------------------------------------------------
# Domains (mirrors the EYLF developmental areas: Physical, Social, Emotional,
# Cognitive, Language — collapsed into the buckets a worksheet can realistically
# target)
# ---------------------------------------------------------------------------

DOMAIN_LITERACY = "Language & Literacy"
DOMAIN_NUMERACY = "Cognitive & Numeracy"
DOMAIN_PROBLEM_SOLVING = "Cognitive & Problem Solving"
DOMAIN_FINE_MOTOR = "Fine Motor & Coordination"
DOMAIN_SENSORY = "Sensory & Physical"
DOMAIN_BODY = "Body Awareness & Physical"

# Five bands. See module docstring point 1 for exactly how each maps back
# to the milestone document.
AGE_GROUPS = [
    "Babies 0-1 years",
    "Toddlers 1-2 years",
    "Toddlers 2-3 years",
    "Preschool 3-4 years",
    "Pre-K 4-5 years",
]

# Babies get cards, not worksheets — see docstring point 2.
NO_WORKSHEET_AGES = {"Babies 0-1 years"}

# ---------------------------------------------------------------------------
# Category catalogue — each entry knows its renderer, its domain, and which
# age groups it's developmentally appropriate for, WITH the specific
# milestone line from the source document that justifies the placement.
# ---------------------------------------------------------------------------

CATEGORY_DEFS = [
    {
        "name": "Look & Point Card",
        "renderer": "look_point",
        "domain": DOMAIN_SENSORY,
        "ages": ["Babies 0-1 years"],
        "milestone_note": "0-4mo/4-8mo: eyes track slow moving target, looks at "
                           "edges/patterns with light-dark contrast and faces.",
    },
    {
        "name": "Point & Name: Objects",
        "renderer": "point_and_name_shapes",
        "domain": DOMAIN_SENSORY,
        "ages": ["Toddlers 1-2 years", "Toddlers 2-3 years"],
        "milestone_note": "1-2y: 'points to objects when named'. 2-3y: "
                           "'recognises and identifies common objects and "
                           "pictures by pointing'.",
    },
    {
        "name": "Point & Name: Body Parts",
        "renderer": "point_and_name_body",
        "domain": DOMAIN_BODY,
        "ages": ["Toddlers 1-2 years"],
        "milestone_note": "1-2y: 'knows some body parts', 'points to body "
                           "parts in a game'.",
    },
    {
        "name": "First Scribbles",
        "renderer": "first_scribbles",
        "domain": DOMAIN_FINE_MOTOR,
        "ages": ["Toddlers 1-2 years"],
        "milestone_note": "1-2y: 'scribbles with pencil or crayon held in "
                           "fist' — free mark-making, not a precise trace.",
    },
    {
        "name": "Fine Motor & Coloring",
        "renderer": "coloring",
        "domain": DOMAIN_FINE_MOTOR,
        "ages": ["Toddlers 1-2 years", "Toddlers 2-3 years", "Preschool 3-4 years"],
        "milestone_note": "General fine-motor / hand-eye coordination practice "
                           "appropriate across the mark-making years.",
    },
    {
        "name": "Trace Big Shapes",
        "renderer": "big_trace",
        "domain": DOMAIN_FINE_MOTOR,
        "ages": ["Toddlers 2-3 years", "Preschool 3-4 years"],
        "milestone_note": "2-3y: 'uses a pencil to draw or scribble in circles "
                           "and lines'. 3-5y: 'imitates variety of shapes in "
                           "drawing, e.g. circles'.",
    },
    {
        "name": "Count Aloud (no writing)",
        "renderer": "count_aloud",
        "domain": DOMAIN_NUMERACY,
        "ages": ["Toddlers 2-3 years"],
        "milestone_note": "2-3y: 'begins to count with numbers' — verbal "
                           "only; writing a digit isn't a milestone until 4-5y.",
    },
    {
        "name": "Sensory / Shape Matching",
        "renderer": "shape_match",
        "domain": DOMAIN_SENSORY,
        "ages": ["Toddlers 2-3 years", "Preschool 3-4 years", "Pre-K 4-5 years"],
        "milestone_note": "2-3y: 'recognises similarities and differences'.",
    },
    {
        "name": "Hollow Letter Fill-In",
        "renderer": "hollow_letter_fill",
        "domain": DOMAIN_LITERACY,
        "ages": ["Preschool 3-4 years"],
        "milestone_note": "3-5y: tripod pencil grip and cutting-paper control "
                           "are established, but full letter-writing/copying "
                           "isn't a listed milestone until 4-5y — a hollow "
                           "outline to color in is the stepping stone.",
    },
    {
        "name": "Shapes & Patterns",
        "renderer": "pattern_complete",
        "domain": DOMAIN_NUMERACY,
        "ages": ["Preschool 3-4 years", "Pre-K 4-5 years"],
        "milestone_note": "3-5y: 'imitates variety of shapes in drawing'; "
                           "predicting/drawing the next shape builds on that.",
    },
    {
        "name": "Problem Solving (odd one out)",
        "renderer": "odd_one_out",
        "domain": DOMAIN_PROBLEM_SOLVING,
        "ages": ["Preschool 3-4 years", "Pre-K 4-5 years"],
        "milestone_note": "3-5y: 'has a longer attention span', 'answers "
                           "simple questions' — sustained visual discrimination.",
    },
    {
        "name": "Body Parts Match",
        "renderer": "body_parts",
        "domain": DOMAIN_BODY,
        "ages": ["Preschool 3-4 years", "Pre-K 4-5 years"],
        "milestone_note": "Matching a number to a printed word needs early "
                           "letter/word recognition, which is a 3-5y-band "
                           "skill (vs. 1-2y's game-based pointing only).",
    },
    {
        "name": "Numeracy (counting & writing)",
        "renderer": "counting",
        "domain": DOMAIN_NUMERACY,
        "ages": ["Pre-K 4-5 years"],
        "milestone_note": "4-5y: 'may write some numbers and letters', "
                           "'counts five to ten things'.",
    },
    {
        "name": "Tracing & Pre-writing (dot to dot)",
        "renderer": "dot_to_dot",
        "domain": DOMAIN_FINE_MOTOR,
        "ages": ["Pre-K 4-5 years"],
        "milestone_note": "4-5y: 'touches objects to count' (number-object "
                           "correspondence) plus established pencil control.",
    },
    {
        "name": "Literacy (letter tracing)",
        "renderer": "tracing_letters",
        "domain": DOMAIN_LITERACY,
        "ages": ["Pre-K 4-5 years"],
        "milestone_note": "4-5y: 'copies letters and may write some "
                           "unprompted'.",
    },
]

CATEGORY_BY_NAME = {c["name"]: c for c in CATEGORY_DEFS}

# Renderer keys that produce a single fixed page (a card, a free-scribble
# space, a coloring page) rather than a scalable set of items — these are
# never given a bonus/stretch section.
NON_TIERED_RENDERERS = {"look_point", "point_and_name_shapes", "point_and_name_body",
                         "coloring", "first_scribbles"}


def categories_for_age(age_group: str) -> list:
    """All catalogue entries appropriate for this age group."""
    return [c for c in CATEGORY_DEFS if age_group in c["ages"]]


# ---------------------------------------------------------------------------
# Shape + color building blocks — real vector graphics, not text
# ---------------------------------------------------------------------------

COLORS = ["#FF6B6B", "#4D96FF", "#FFD93D", "#6BCB77", "#B983FF", "#FF9F45", "#3DDBD9"]

SHAPE_PATHS = {
    "circle": '<circle cx="60" cy="60" r="50" fill="{c}" stroke="#333" stroke-width="5"/>',
    "square": '<rect x="15" y="15" width="90" height="90" fill="{c}" stroke="#333" stroke-width="5"/>',
    "triangle": '<polygon points="60,10 112,108 8,108" fill="{c}" stroke="#333" stroke-width="5" stroke-linejoin="round"/>',
    "rectangle": '<rect x="8" y="30" width="104" height="60" fill="{c}" stroke="#333" stroke-width="5"/>',
    "star": '<polygon points="60,5 73,43 115,43 81,66 93,105 60,82 27,105 39,66 5,43 47,43" fill="{c}" stroke="#333" stroke-width="5" stroke-linejoin="round"/>',
    "hexagon": '<polygon points="30,10 90,10 115,60 90,110 30,110 5,60" fill="{c}" stroke="#333" stroke-width="5" stroke-linejoin="round"/>',
    "heart": '<path d="M60 105 C10 65,10 25,40 15 C55 10,60 30,60 35 C60 30,65 10,80 15 C110 25,110 65,60 105 Z" fill="{c}" stroke="#333" stroke-width="5"/>',
}

SHAPE_NAMES = list(SHAPE_PATHS.keys())

# Bold outline-only versions (no fill) for coloring pages
OUTLINE_EXTRAS = {
    "flower": '<circle cx="60" cy="60" r="16" fill="none" stroke="#333" stroke-width="5"/><circle cx="60" cy="30" r="20" fill="none" stroke="#333" stroke-width="5"/><circle cx="60" cy="90" r="20" fill="none" stroke="#333" stroke-width="5"/><circle cx="30" cy="60" r="20" fill="none" stroke="#333" stroke-width="5"/><circle cx="90" cy="60" r="20" fill="none" stroke="#333" stroke-width="5"/>',
    "butterfly": '<path d="M60 25 C35 5,10 25,18 55 C25 85,50 78,60 60 C70 78,95 85,102 55 C110 25,85 5,60 25 Z" fill="none" stroke="#333" stroke-width="5"/><line x1="60" y1="25" x2="60" y2="105" stroke="#333" stroke-width="5"/>',
    "fish": '<ellipse cx="55" cy="60" rx="45" ry="28" fill="none" stroke="#333" stroke-width="5"/><polygon points="98,60 118,42 118,78" fill="none" stroke="#333" stroke-width="5"/><circle cx="30" cy="52" r="4" fill="#333"/>',
    "tree": '<rect x="52" y="80" width="16" height="35" fill="none" stroke="#333" stroke-width="5"/><circle cx="60" cy="50" r="42" fill="none" stroke="#333" stroke-width="5"/>',
}

LETTERS = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
NUMBERS = list(range(1, 11))

DOT_SHAPES = {
    "star": [(150, 10), (180, 90), (270, 90), (200, 140), (225, 220), (150, 175), (75, 220), (100, 140), (30, 90), (120, 90)],
    "house": [(150, 20), (260, 100), (230, 100), (230, 230), (70, 230), (70, 100), (40, 100)],
    "fish": [(30, 130), (90, 90), (160, 90), (220, 60), (270, 130), (220, 200), (160, 170), (90, 170)],
    "boat": [(40, 180), (40, 100), (100, 100), (100, 40), (140, 100), (260, 100), (220, 180)],
}

# Fixed coordinate map for the body-parts stick figure (viewBox 0 0 300 320)
BODY_PART_COORDS = {
    "head": (150, 45),
    "eyes": (140, 42),
    "nose": (150, 50),
    "mouth": (150, 58),
    "ears": (172, 45),
    "shoulders": (150, 95),
    "hands": (95, 150),
    "tummy": (150, 145),
    "knees": (150, 225),
    "feet": (150, 275),
}

# The order below controls difficulty ramp: earliest = biggest/most obvious parts
BODY_PART_DIFFICULTY_ORDER = ["head", "hands", "feet", "tummy", "eyes", "mouth", "shoulders", "knees", "nose", "ears"]

STICK_FIGURE_OUTLINE = """
<circle cx="150" cy="45" r="35" fill="#FFD9B3" stroke="#333" stroke-width="4"/>
<line x1="150" y1="80" x2="150" y2="210" stroke="#333" stroke-width="8" stroke-linecap="round"/>
<line x1="150" y1="95" x2="95" y2="150" stroke="#333" stroke-width="8" stroke-linecap="round"/>
<line x1="150" y1="95" x2="205" y2="150" stroke="#333" stroke-width="8" stroke-linecap="round"/>
<line x1="150" y1="210" x2="105" y2="290" stroke="#333" stroke-width="8" stroke-linecap="round"/>
<line x1="150" y1="210" x2="195" y2="290" stroke="#333" stroke-width="8" stroke-linecap="round"/>
"""


def shape_svg(name, color, size=90):
    path = SHAPE_PATHS.get(name, SHAPE_PATHS["circle"]).format(c=color)
    return f'<svg viewBox="0 0 120 120" width="{size}" height="{size}">{path}</svg>'


def pick_shapes(avoid_titles, n):
    """Pick n shapes not recently referenced by name in avoid_titles, cycling through the set."""
    avoid_text = " ".join(avoid_titles).lower()
    pool = [s for s in SHAPE_NAMES if s not in avoid_text] or SHAPE_NAMES
    random.shuffle(pool)
    return (pool * ((n // len(pool)) + 1))[:n]


# ---------------------------------------------------------------------------
# Difficulty: age-aware baseline + feedback nudge
# ---------------------------------------------------------------------------

DIFFICULTY_LEVELS = ["easy", "medium", "hard"]

AGE_BASE_DIFFICULTY = {
    "Toddlers 1-2 years": "easy",
    "Toddlers 2-3 years": "easy",
    "Preschool 3-4 years": "medium",
    "Pre-K 4-5 years": "medium",
}


def difficulty_for(age_group: str, feedback_text: str) -> str:
    """Starts from an age-appropriate baseline, then nudges one step up/down
    based on the educator's free-text feedback (keyword heuristic — no LLM
    call needed, so it's fast and always available)."""
    base = AGE_BASE_DIFFICULTY.get(age_group, "easy")
    idx = DIFFICULTY_LEVELS.index(base)

    if feedback_text:
        t = feedback_text.lower()
        if "too easy" in t or "harder" in t or "more difficult" in t or "more challenging" in t:
            idx = min(idx + 1, len(DIFFICULTY_LEVELS) - 1)
        elif "too hard" in t or "too difficult" in t or "easier" in t or "simplify" in t:
            idx = max(idx - 1, 0)

    return DIFFICULTY_LEVELS[idx]


def _next_difficulty(difficulty: str) -> str:
    idx = DIFFICULTY_LEVELS.index(difficulty)
    return DIFFICULTY_LEVELS[min(idx + 1, len(DIFFICULTY_LEVELS) - 1)]


# ---------------------------------------------------------------------------
# Visual renderers — each returns (instructions, inner HTML/SVG content)
# ---------------------------------------------------------------------------

def render_look_point(avoid_titles, difficulty):
    """0-1y: one giant, high-contrast shape for the educator to hold up and
    narrate. Not something baby completes — no writing, no fine motor
    demand at all, matching 'tracks slow moving object', 'looks at
    edges/patterns with light-dark contrast and faces'."""
    avoid_text = " ".join(avoid_titles).lower()
    choices = [s for s in SHAPE_NAMES if s not in avoid_text] or SHAPE_NAMES
    shape = random.choice(choices)
    color = random.choice(COLORS)
    big = f'<svg viewBox="0 0 120 120" width="360" height="360">{SHAPE_PATHS[shape].format(c=color)}</svg>'
    instructions = ("For the educator: hold this card about 20-30cm from baby's face. "
                     "Name the shape and color slowly, then pause so baby can look and study it.")
    return instructions, f'<div class="coloring-box">{big}</div>'


def render_point_and_name_shapes(avoid_titles, difficulty):
    """1-2y/2-3y: 'points to objects when named' / 'recognises and
    identifies common objects and pictures by pointing'. A reference card
    for the naming game, not a task the child fills in."""
    shapes = pick_shapes(avoid_titles, 3)
    items = ""
    for shape in shapes:
        color = random.choice(COLORS)
        items += (f'<div class="point-name-item">{shape_svg(shape, color, size=110)}'
                   f'<div class="point-name-label">{shape}</div></div>')
    instructions = "Say each shape's name out loud and ask your child to point to it."
    return instructions, f'<div class="point-name-row">{items}</div>'


def render_point_and_name_body(avoid_titles, difficulty):
    """1-2y: 'knows some body parts', 'points to body parts in a game'.
    No reading required — the word is printed only for the educator/parent."""
    avoid_text = " ".join(avoid_titles).lower()
    ordered = [p for p in BODY_PART_DIFFICULTY_ORDER if p not in avoid_text] or BODY_PART_DIFFICULTY_ORDER
    parts = ordered[:3]
    dots = ""
    labels = []
    for part in parts:
        x, y = BODY_PART_COORDS[part]
        dots += f'<circle cx="{x}" cy="{y}" r="10" fill="#FFD93D" stroke="#333" stroke-width="3"/>'
        labels.append(part)
    svg = f'<svg viewBox="0 0 300 320" width="260" height="280">{STICK_FIGURE_OUTLINE}{dots}</svg>'
    legend = "".join(f'<div class="legend-item">{p}</div>' for p in labels)
    instructions = "Say each body part word aloud and ask your child to point to it on the picture or on themselves."
    return instructions, f'<div class="body-parts-row"><div class="coloring-box">{svg}</div><div class="legend">{legend}</div></div>'


def render_first_scribbles(avoid_titles, difficulty):
    """1-2y: 'scribbles with pencil or crayon held in fist' — free
    mark-making inside a big blank shape, not a precise trace."""
    blob = ('<path d="M60 15 C95 10,110 40,105 65 C100 95,80 110,55 108 '
            'C25 105,10 80,15 50 C18 28,32 18,60 15 Z" fill="white" '
            'stroke="#333" stroke-width="5" stroke-dasharray="10,6"/>')
    svg = f'<svg viewBox="0 0 120 120" width="320" height="320">{blob}</svg>'
    instructions = "Let your child scribble freely inside the big shape with a crayon. Any marks count!"
    return instructions, f'<div class="coloring-box">{svg}</div>'


def render_shape_match(avoid_titles, difficulty):
    rows = {"easy": 3, "medium": 4, "hard": 5}[difficulty]
    shapes = pick_shapes(avoid_titles, rows)
    row_html = ""
    for shape in shapes:
        color_a = random.choice(COLORS)
        color_b = color_a if random.random() > 0.5 else random.choice([c for c in COLORS if c != color_a])
        cells = "".join(
            f'<div class="cell">{shape_svg(shape, color_a)}</div><div class="cell">{shape_svg(shape, color_b)}</div>'
        )
        row_html += f'<div class="match-row">{cells}<div class="answer-circle">SAME&nbsp;&nbsp;&nbsp;DIFFERENT</div></div>'
    instructions = "Look at each pair. Circle SAME if they match, or DIFFERENT if they don't."
    return instructions, f'<div class="grid">{row_html}</div>'


def render_big_trace(avoid_titles, difficulty):
    """2-3y/3-4y: pencil control for circles/lines, then imitating a
    variety of shapes. Big dashed outlines to trace, sized down slightly
    as difficulty rises (bigger target = easier for less control)."""
    count = {"easy": 2, "medium": 3, "hard": 4}[difficulty]
    size = {"easy": 170, "medium": 140, "hard": 120}[difficulty]
    shapes = pick_shapes(avoid_titles, count)
    items = ""
    for shape in shapes:
        raw = SHAPE_PATHS[shape].format(c="none")
        raw = raw.replace('stroke-width="5"', 'stroke-width="4" stroke-dasharray="9,5"')
        items += f'<div class="cell"><svg viewBox="0 0 120 120" width="{size}" height="{size}">{raw}</svg></div>'
    instructions = "Trace over each shape's dashed outline with a finger first, then with a crayon."
    return instructions, f'<div class="pattern-row">{items}</div>'


def render_count_aloud(avoid_titles, difficulty):
    """2-3y: 'begins to count with numbers' — verbal only, no writing
    skill yet, so no answer box, just objects to count together."""
    max_count = {"easy": 3, "medium": 4, "hard": 5}[difficulty]
    rows = 3
    shapes = pick_shapes(avoid_titles, rows)
    row_html = ""
    for shape in shapes:
        count = random.randint(2, max_count)
        color = random.choice(COLORS)
        icons = "".join(shape_svg(shape, color, size=55) for _ in range(count))
        row_html += f'<div class="count-row"><div class="icons">{icons}</div></div>'
    instructions = "Count each row together out loud. Ask: 'How many do you see?'"
    return instructions, f'<div class="grid">{row_html}</div>'


def render_counting(avoid_titles, difficulty):
    max_count = {"easy": 5, "medium": 8, "hard": 10}[difficulty]
    rows = 4
    shapes = pick_shapes(avoid_titles, rows)
    row_html = ""
    for shape in shapes:
        count = random.randint(2, max_count)
        color = random.choice(COLORS)
        icons = "".join(shape_svg(shape, color, size=45) for _ in range(count))
        row_html += f'<div class="count-row"><div class="icons">{icons}</div><div class="answer-box">?</div></div>'
    instructions = "Count how many shapes are in each row and write the number in the box."
    return instructions, f'<div class="grid">{row_html}</div>'


def render_coloring(avoid_titles, difficulty):
    pool = {**{k: SHAPE_PATHS[k].format(c="none") for k in SHAPE_NAMES}, **OUTLINE_EXTRAS}
    avoid_text = " ".join(avoid_titles).lower()
    choices = [k for k in pool if k not in avoid_text] or list(pool.keys())
    name = random.choice(choices)
    svg_inner = pool[name]
    big = f'<svg viewBox="0 0 120 120" width="320" height="320">{svg_inner}</svg>'
    instructions = "Color me in! Use as many colors as you like."
    return instructions, f'<div class="coloring-box">{big}</div>'


def render_hollow_letter_fill(avoid_titles, difficulty):
    """3-4y: hollow/outline letters as a fill-in stepping stone ahead of
    full letter-writing, which the doc places at 4-5y."""
    count = {"easy": 2, "medium": 3, "hard": 4}[difficulty]
    avoid_text = " ".join(avoid_titles).upper()
    choices = [l for l in LETTERS if l not in avoid_text] or LETTERS
    letters = random.sample(choices, min(count, len(choices)))
    items = ""
    for letter in letters:
        svg = (f'<svg viewBox="0 0 120 120" width="110" height="110">'
               f'<text x="60" y="95" font-size="105" font-family="Arial, sans-serif" '
               f'font-weight="bold" text-anchor="middle" fill="white" '
               f'stroke="#333" stroke-width="4">{letter}</text></svg>')
        items += f'<div class="cell">{svg}</div>'
    instructions = "Color inside each hollow letter to fill it in completely."
    return instructions, f'<div class="pattern-row">{items}</div>'


def render_pattern_complete(avoid_titles, difficulty):
    length = {"easy": 4, "medium": 6, "hard": 8}[difficulty]
    shape_a, shape_b = pick_shapes(avoid_titles, 2)
    color_a, color_b = random.sample(COLORS, 2)
    sequence = []
    for i in range(length):
        sequence.append((shape_a, color_a) if i % 2 == 0 else (shape_b, color_b))
    icons = "".join(shape_svg(s, c, size=70) for s, c in sequence)
    blank = '<div class="blank-box">?</div>'
    instructions = "What comes next? Draw and color the missing shape in the empty box."
    return instructions, f'<div class="pattern-row">{icons}{blank}</div>'


def render_odd_one_out(avoid_titles, difficulty):
    rows = {"easy": 2, "medium": 3, "hard": 4}[difficulty]
    shapes = pick_shapes(avoid_titles, rows)
    row_html = ""
    for shape in shapes:
        base_color = random.choice(COLORS)
        odd_color = random.choice([c for c in COLORS if c != base_color])
        positions = [base_color] * 4
        odd_index = random.randint(0, 3)
        positions[odd_index] = odd_color
        icons = "".join(f'<div class="cell">{shape_svg(shape, c)}</div>' for c in positions)
        row_html += f'<div class="match-row">{icons}</div>'
    instructions = "Circle the shape in each row that is different from the others."
    return instructions, f'<div class="grid">{row_html}</div>'


def render_tracing_letters(avoid_titles, difficulty):
    reps = {"easy": 2, "medium": 3, "hard": 4}[difficulty]
    avoid_text = " ".join(avoid_titles).upper()
    choices = [l for l in LETTERS if l not in avoid_text] or LETTERS
    letters = random.sample(choices, min(3, len(choices)))
    row_html = ""
    for letter in letters:
        big_letters = "".join(f'<span class="trace-letter">{letter}</span>' for _ in range(reps))
        row_html += f'<div class="trace-row">{big_letters}</div>'
    instructions = "Trace over each letter with your finger, then with a pencil or crayon."
    return instructions, f'<div class="grid">{row_html}</div>'


def render_dot_to_dot(avoid_titles, difficulty):
    avoid_text = " ".join(avoid_titles).lower()
    choices = [k for k in DOT_SHAPES if k not in avoid_text] or list(DOT_SHAPES.keys())
    name = random.choice(choices)
    points = DOT_SHAPES[name]
    if difficulty == "easy":
        points = points[:max(4, len(points) // 2)]
    dots = ""
    for i, (x, y) in enumerate(points, start=1):
        dots += f'<circle cx="{x}" cy="{y}" r="6" fill="#333"/><text x="{x+10}" y="{y+5}" font-size="16" font-weight="bold" fill="#333">{i}</text>'
    svg = f'<svg viewBox="0 0 300 260" width="320" height="280">{dots}</svg>'
    instructions = "Join the dots in order from 1 to the end to reveal a picture, then color it in!"
    return instructions, f'<div class="coloring-box">{svg}</div>'


def render_body_parts(avoid_titles, difficulty):
    """A stick figure with numbered points the child matches to a word
    list. Difficulty controls how many (and how subtle) the parts are, and
    whether the word list is shuffled (harder) or in figure order (easier)."""
    count = {"easy": 3, "medium": 5, "hard": 7}[difficulty]
    avoid_text = " ".join(avoid_titles).lower()
    ordered = [p for p in BODY_PART_DIFFICULTY_ORDER if p not in avoid_text] or BODY_PART_DIFFICULTY_ORDER
    parts = ordered[:count]

    dots = ""
    legend_items = []
    for i, part in enumerate(parts, start=1):
        x, y = BODY_PART_COORDS[part]
        dots += f'<circle cx="{x}" cy="{y}" r="9" fill="#FFD93D" stroke="#333" stroke-width="3"/><text x="{x}" y="{y+5}" font-size="14" font-weight="bold" fill="#333" text-anchor="middle">{i}</text>'
        legend_items.append((i, part))

    word_order = legend_items if difficulty == "easy" else random.sample(legend_items, len(legend_items))
    legend_html = "".join(
        f'<div class="legend-item"><span class="legend-num">{i}</span> {part}</div>' for i, part in word_order
    )

    svg = f'<svg viewBox="0 0 300 320" width="260" height="280">{STICK_FIGURE_OUTLINE}{dots}</svg>'
    instructions = "Match each number on the picture to its body part word. Say the word out loud!"
    body_html = f'<div class="body-parts-row"><div class="coloring-box">{svg}</div><div class="legend">{legend_html}</div></div>'
    return instructions, body_html


RENDERERS = {
    "look_point": render_look_point,
    "point_and_name_shapes": render_point_and_name_shapes,
    "point_and_name_body": render_point_and_name_body,
    "first_scribbles": render_first_scribbles,
    "shape_match": render_shape_match,
    "big_trace": render_big_trace,
    "count_aloud": render_count_aloud,
    "counting": render_counting,
    "coloring": render_coloring,
    "hollow_letter_fill": render_hollow_letter_fill,
    "pattern_complete": render_pattern_complete,
    "odd_one_out": render_odd_one_out,
    "tracing_letters": render_tracing_letters,
    "dot_to_dot": render_dot_to_dot,
    "body_parts": render_body_parts,
}

CATEGORY_TITLES = {
    "look_point": "Look & Point Card",
    "point_and_name_shapes": "Point & Name",
    "point_and_name_body": "Point to My Body Parts",
    "first_scribbles": "Scribble Time!",
    "shape_match": "Same or Different?",
    "big_trace": "Trace the Shapes",
    "count_aloud": "Let's Count Together",
    "counting": "Count and Write",
    "coloring": "Color Me In!",
    "hollow_letter_fill": "Fill the Hollow Letters",
    "pattern_complete": "What Comes Next?",
    "odd_one_out": "Spot the Difference",
    "tracing_letters": "Letter Tracing",
    "dot_to_dot": "Dot to Dot",
    "body_parts": "Match My Body",
}

# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def get_week_key(d: datetime.date = None) -> str:
    d = d or datetime.date.today()
    iso = d.isocalendar()
    return f"{iso[0]}-W{iso[1]:02d}"


def get_week_index(d: datetime.date = None) -> int:
    d = d or datetime.date.today()
    return (d - datetime.date(2020, 1, 6)).days // 7


def get_categories_for_week(week_index: int, age_group: str, n: int = 3) -> list:
    """Returns n category names appropriate for age_group, rotating through
    that age group's available categories so that, across consecutive
    weeks, every developmental DOMAIN gets covered rather than just
    whichever categories happen to come up first.

    n can exceed the number of distinct categories available for a young
    age group — in that case categories simply repeat within the week,
    which is fine since the shapes/colors/body-parts/letters chosen are
    still randomized per worksheet, and each repeat also gets its own
    bonus/stretch section (see render_with_bonus).
    """
    available = categories_for_age(age_group)
    if not available:
        available = CATEGORY_DEFS  # fallback safety net

    # Order by domain first so consecutive picks favour domain variety,
    # then rotate the start point by week so different weeks lead with
    # different domains too.
    by_domain = sorted(available, key=lambda c: c["domain"])
    pool_len = len(by_domain)
    start = (week_index * n) % pool_len
    picks = [by_domain[(start + i) % pool_len] for i in range(n)]
    return [c["name"] for c in picks]


def render_with_bonus(renderer_key: str, avoid_titles: list, difficulty: str):
    """Runs the base renderer at `difficulty`, then — for renderer types
    that can scale (grids, counts, tracing sets, etc.) — appends an
    optional bonus section one difficulty step up, so a worksheet is never
    a single static item. Card/coloring/free-scribble types are single-page
    by nature and are returned as-is."""
    instructions, body_html = RENDERERS[renderer_key](avoid_titles, difficulty)

    if renderer_key in NON_TIERED_RENDERERS:
        return instructions, body_html

    bonus_difficulty = _next_difficulty(difficulty)
    if bonus_difficulty == difficulty:
        return instructions, body_html

    bonus_instructions, bonus_html = RENDERERS[renderer_key](avoid_titles, bonus_difficulty)
    combined = (
        f'{body_html}'
        f'<div class="bonus-box">'
        f'<div class="bonus-label">⭐ Extra challenge (optional):</div>'
        f'<div class="instructions">{bonus_instructions}</div>'
        f'{bonus_html}'
        f'</div>'
    )
    return instructions, combined


def _maybe_get_ai_title(client, category, age_group, theme, fallback_title):
    """Optional: ask the AI for a fun 3-6 word title. If this fails for any
    reason (rate limit, network, bad response) we silently keep the
    deterministic fallback — the worksheet never depends on this working."""
    try:
        prompt = f"Give ONE fun, short (3-6 word) worksheet title for a {age_group} '{category}' activity" + (f" themed around '{theme}'" if theme else "") + ". Reply with ONLY the title, nothing else."
        resp = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=20,
        )
        title = resp.choices[0].message.content.strip().strip('"')
        return title if 2 <= len(title) <= 60 else fallback_title
    except Exception:
        return fallback_title


def generate_worksheet(client, age_group: str, category: str, theme: str, avoid_topics: list, feedback_text: str) -> dict:
    cat_def = CATEGORY_BY_NAME.get(category)
    renderer_key = cat_def["renderer"] if cat_def else "coloring"
    domain = cat_def["domain"] if cat_def else DOMAIN_SENSORY
    difficulty = difficulty_for(age_group, feedback_text)
    instructions, body_html = render_with_bonus(renderer_key, avoid_topics, difficulty)

    fallback_title = CATEGORY_TITLES.get(renderer_key, "Worksheet")
    title = _maybe_get_ai_title(client, category, age_group, theme, fallback_title) if client else fallback_title

    html = _render_worksheet_html(title, category, age_group, domain, instructions, body_html)
    return {"title": title, "html": html, "category": category, "domain": domain}


WORKSHEET_CSS = """
body { font-family: 'Comic Sans MS', 'Trebuchet MS', sans-serif; background: #fffbe8; margin: 0; padding: 20px; }
.sheet { border: 10px solid transparent; border-image: linear-gradient(90deg, #FF6B6B, #FFD93D, #6BCB77, #4D96FF) 1; padding: 20px; background: white; border-radius: 16px; }
h1 { color: #FF6B6B; text-align: center; font-size: 28px; margin-bottom: 4px; }
.meta { text-align: center; color: #888; font-size: 13px; margin-bottom: 10px; }
.instructions { text-align: center; color: #444; font-size: 15px; margin-bottom: 18px; font-weight: bold; }
.grid { display: flex; flex-direction: column; gap: 14px; }
.match-row { display: flex; align-items: center; gap: 10px; border: 2px dashed #ccc; border-radius: 10px; padding: 8px; }
.cell { display: flex; align-items: center; justify-content: center; }
.answer-circle { margin-left: auto; font-size: 13px; color: #666; border: 2px solid #ccc; border-radius: 20px; padding: 4px 10px; }
.count-row { display: flex; align-items: center; gap: 14px; border: 2px dashed #ccc; border-radius: 10px; padding: 8px; }
.icons { display: flex; flex-wrap: wrap; gap: 4px; flex: 1; }
.answer-box { width: 50px; height: 50px; border: 3px solid #333; border-radius: 8px; display: flex; align-items: center; justify-content: center; font-size: 22px; color: #ccc; }
.coloring-box { display: flex; justify-content: center; margin: 20px 0; }
.pattern-row { display: flex; align-items: center; gap: 10px; justify-content: center; flex-wrap: wrap; }
.blank-box { width: 70px; height: 70px; border: 3px dashed #333; border-radius: 8px; display: flex; align-items: center; justify-content: center; font-size: 30px; color: #ccc; }
.trace-row { display: flex; gap: 20px; justify-content: center; }
.trace-letter { font-size: 70px; font-weight: bold; color: #ddd; -webkit-text-stroke: 1px #999; }
.body-parts-row { display: flex; align-items: center; justify-content: center; gap: 30px; flex-wrap: wrap; }
.legend { display: flex; flex-direction: column; gap: 10px; font-size: 18px; color: #333; }
.legend-item { display: flex; align-items: center; gap: 8px; }
.legend-num { background: #FFD93D; border: 2px solid #333; border-radius: 50%; width: 26px; height: 26px; display: inline-flex; align-items: center; justify-content: center; font-weight: bold; font-size: 14px; }
.point-name-row { display: flex; justify-content: center; gap: 30px; flex-wrap: wrap; margin: 10px 0; }
.point-name-item { display: flex; flex-direction: column; align-items: center; gap: 8px; }
.point-name-label { font-size: 16px; font-weight: bold; color: #444; text-transform: capitalize; }
.bonus-box { margin-top: 22px; border: 3px dashed #FFD93D; border-radius: 12px; padding: 14px; background: #fffdf2; }
.bonus-label { text-align: center; font-weight: bold; color: #B98A00; margin-bottom: 8px; font-size: 15px; }
@media print { body { background: white; } }
"""


def _render_worksheet_html(title, category, age_group, domain, instructions, body_html):
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>{WORKSHEET_CSS}</style>
</head>
<body>
  <div class="sheet">
    <h1>🌟 {title} 🌟</h1>
    <div class="meta">{category} &middot; {domain} &middot; {age_group}</div>
    <div class="instructions">{instructions}</div>
    {body_html}
  </div>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Streamlit tab
# ---------------------------------------------------------------------------

def worksheet_tab(client):
    init_worksheet_tables()

    st.subheader("🖍️ Weekly Worksheet Generator")
    st.caption("Visual worksheets that rotate through every developmental domain for the chosen age group "
               "— literacy, numeracy, fine motor, sensory, body awareness and problem-solving — colorful "
               "pages the children can actually color, trace, match or draw on, not instructions to read.")

    col_age, col_freq = st.columns(2)
    with col_age:
        age_group = st.selectbox(
            "Which group are these worksheets for?",
            AGE_GROUPS,
            key="worksheet_age_group",
        )
    with col_freq:
        current_freq = get_worksheets_per_week(age_group, default=3)
        worksheets_per_week = st.selectbox(
            "Cards per week for this group" if age_group in NO_WORKSHEET_AGES else "Worksheets per week for this group",
            [2, 3, 4, 5],
            index=[2, 3, 4, 5].index(current_freq) if current_freq in [2, 3, 4, 5] else 1,
            key=f"worksheet_freq_{age_group}",
        )
        if worksheets_per_week != current_freq:
            set_worksheets_per_week(age_group, worksheets_per_week)

    if age_group in NO_WORKSHEET_AGES:
        st.info(
            "Babies this age don't complete worksheets — they can't hold a pencil purposefully yet. "
            "Instead this generates 'Look & Point' cards: big, high-contrast shapes for you to hold up "
            "and narrate slowly during floor time or tummy time."
        )

    theme = st.text_input("This week's theme (optional — leave blank for variety)", key="worksheet_theme")

    week_key = get_week_key()
    week_index = get_week_index()

    # Categories genuinely appropriate for the CURRENTLY SELECTED age group.
    # A worksheet saved under an old category set (e.g. generated before an
    # age-rules update, or after the educator changes age group mid-week)
    # won't match this — we keep it visible but flagged, never silently
    # counted as "ready".
    valid_category_names = {c["name"] for c in categories_for_age(age_group)}

    all_existing = get_worksheets_for_week(week_key, age_group)
    existing = [w for w in all_existing if w["category"] in valid_category_names]
    outdated = [w for w in all_existing if w["category"] not in valid_category_names]

    existing_categories = {w["category"] for w in existing}
    target_categories = get_categories_for_week(week_index, age_group, n=worksheets_per_week)
    missing_categories = [c for c in target_categories if c not in existing_categories]

    item_word = "cards" if age_group in NO_WORKSHEET_AGES else "worksheets"
    st.markdown(f"**Week: {week_key}** — {len(existing)}/{worksheets_per_week} {item_word} ready for {age_group}")

    if outdated:
        st.warning(
            f"{len(outdated)} saved item(s) for this week don't match {age_group}'s current "
            "activity types (likely generated before an update, or under a different age group) "
            "and are NOT counted above or shown to families. Review them below."
        )

    if missing_categories:
        st.info("Not all of this week's " + item_word + " exist yet: " + ", ".join(missing_categories))
        if st.button("✨ Auto-generate this week's remaining " + item_word, type="primary"):
            feedback_text = get_latest_feedback(age_group)
            avoid_topics = get_recent_titles(age_group, lookback_weeks=8)
            with st.spinner("Generating..."):
                for cat in missing_categories:
                    ws = generate_worksheet(client, age_group, cat, theme, avoid_topics, feedback_text)
                    save_worksheet(week_key, age_group, cat, ws["title"], ws["html"], source="auto")
                    avoid_topics.append(ws["title"])
            st.success(f"This week's {item_word} are ready.")
            st.rerun()
    else:
        st.success(f"All {worksheets_per_week} {item_word} for this week are ready. ✅")

    if existing:
        st.markdown(f"#### This week's {item_word}")
        for w in existing:
            with st.expander(f"{w['category']} — {w['title']}"):
                st.components.v1.html(w["html_content"], height=650, scrolling=True)
                col_dl, col_regen = st.columns([3, 1])
                with col_dl:
                    st.download_button(
                        "Download (HTML — open and print/save as PDF from your browser)",
                        data=w["html_content"],
                        file_name=f"{week_key}_{w['category'][:15]}.html",
                        mime="text/html",
                        key=f"dl_{w['id']}",
                    )
                with col_regen:
                    if st.button("🔄 Regenerate", key=f"regen_{w['id']}",
                                 help="Delete this one and make a fresh version — use this if it looks off "
                                      "(e.g. after you've updated the app's code) since existing items "
                                      "are never auto-replaced."):
                        delete_worksheet(w["id"])
                        feedback_text = get_latest_feedback(age_group)
                        avoid_topics = get_recent_titles(age_group, lookback_weeks=8)
                        ws = generate_worksheet(client, age_group, w["category"], theme, avoid_topics, feedback_text)
                        save_worksheet(week_key, age_group, w["category"], ws["title"], ws["html"], source="auto")
                        st.rerun()

        with st.expander("Start this week over for " + age_group):
            st.caption(
                f"Deletes every saved item for this age group and week so the next auto-generate "
                f"builds them fresh — useful right after you update the app's code, since existing "
                f"{item_word} are cached and won't update on their own."
            )
            if st.button("🗑️ Clear all of this week's " + item_word, key="clear_week"):
                for w in existing:
                    delete_worksheet(w["id"])
                st.rerun()

    if outdated:
        with st.expander(f"⚠️ Outdated items for this week ({len(outdated)}) — not shown to families"):
            for w in outdated:
                col_a, col_b = st.columns([4, 1])
                with col_a:
                    st.write(f"**{w['category']}** — {w['title']}")
                with col_b:
                    if st.button("Remove", key=f"del_{w['id']}"):
                        delete_worksheet(w["id"])
                        st.rerun()

    st.divider()
    st.markdown("#### Or request a specific one")
    age_categories = [c["name"] for c in categories_for_age(age_group)]
    col1, col2 = st.columns(2)
    with col1:
        manual_category = st.selectbox("Category (age-appropriate for " + age_group + ")", age_categories, key="manual_ws_category")
    with col2:
        manual_note = st.text_input("Theme hint (optional)", key="manual_ws_note")
    if st.button("Generate this one"):
        feedback_text = get_latest_feedback(age_group)
        avoid_topics = get_recent_titles(age_group, lookback_weeks=8)
        with st.spinner("Generating..."):
            ws = generate_worksheet(client, age_group, manual_category, manual_note or theme, avoid_topics, feedback_text)
            save_worksheet(week_key, age_group, manual_category, ws["title"], ws["html"], source="manual")
        st.success("Generated!")
        st.components.v1.html(ws["html"], height=650, scrolling=True)
        st.rerun()

    st.divider()
    st.markdown("#### Feedback for next week's difficulty")
    st.caption("Tell it in your own words how this week's items landed — it'll shape next week's difficulty automatically.")
    feedback_input = st.text_area("e.g. 'Numeracy was too easy, literacy was just right'", key="ws_feedback_input")
    if st.button("Save feedback"):
        save_feedback(age_group, week_key, feedback_input)
        st.success(f"Saved — next week's {item_word} will take this into account.")

    with st.expander("📚 Past history (avoid-repeat log)"):
        history = get_worksheet_history(age_group)
        if not history:
            st.caption("No history yet.")
        for w in history:
            st.write(f"**{w['week_key']}** — {w['category']}: {w['title']} _(source: {w['source']})_")